env:
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  '@typescript-eslint/semi': [2, 'always']
  '@typescript-eslint/comma-dangle': [2, 'only-multiline']
  '@typescript-eslint/no-misused-promises': 0
  '@typescript-eslint/member-delimiter-style':
    [
      2,
      {
        'multiline': { 'delimiter': 'semi', 'requireLast': true },
        'singleline': { 'delimiter': 'semi', 'requireLast': false },
        'multilineDetection': 'brackets',
      },
    ]
